### ISSUE TITLE
TO DO Before SGV4

### ISSUE THREAD

**Issue by remotevase** [Inactive-to-Reactive/SurvivalGamesV4#1]
- [x] Add random chest spawning
- [x] Customization for chance that a chest will spawn
- [x] Add onleave event
- [x] Add grace period unstable (not tested)
- [x] Add grace period stable
- [x] Fix a few other issues
- [x] Add more config features
- [x] Add **option** to enable/disable lightning on death
- [x] Fix winner TP to spawn
- [x] Make the ImagicalMine Branch Stable
- [x] Update Genysis branch (after the above is completed)
- [x] Send messages only to people in SG world

**Comment by Mike4l6** [comment]
refill chests?

**Comment by remotevase** [comment]
Already done
