### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by padrone21** [Inactive-to-Reactive/SurvivalGamesV4#12]
ImagicalMine Crash Dump Tue Jun 14 18:35:36 MSK 2016

Error: Constant expression contains invalid operations
File: /SGV4.0.2.phar/src/SurvivalGamesV4/SurvivalGamesV4
Line: 41
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[32] use pocketmine\tile\Chest;
[33] use pocketmine\inventory\ChestInventory;
[34] use pocketmine\event\plugin\PluginEvent;
[35] use pocketmine\entity\Entity;
[36] use pocketmine\network\protocol\AddEntityPacket;
[37] use pocketmine\event\entity\EntityDamageByEntityEvent;
[38] 
[39] class SurvivalGamesV4 extends PluginBase implements Listener {
[40] 	
[41] 	public $sgprefix = $this->getConfig()->get("SG_Prefix");
[42]     	public $prefix = $sgprefix;
[43] 	public $mode = 0;
[44] 	public $arenas = array();
[45] 	public $currentLevel = "";
[46] 	
[47] 	public function onEnable()
[48] 	{
[49]         $this->getServer()->getPluginManager()->registerEvents($this ,$this);
[50] 		$this->getLogger()->info(C::GREEN . "SurvivalGamesV4 (V4.0.2) Loaded!");
[51] 		$this->saveResource("/rank.yml");

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ImagicalMine version: 1.4 #0 [Protocol 70; API 2.0.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux ns502620.ip-198-27-68.net 2.6.32-openvz-amd64 #1 SMP Thu Mar 6 16:34:46 MSK 2014 x86_64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
ImagicalDevTools 1.4.1 by PocketMine Team and modyfied by DarkWav for API(s) 2.1.0, 2.0.0, 1.14.0
DisableHungerPerWorld 1.0_Dev by Mineboy210 for API(s) 1.14.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
SexyMOTD 1.0.0 by hoyinm14mc for API(s) 1.14.0, 2.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWmtz48ax/SsTrqss3SIoviXRJSfKSl5vrrRiRG32g+lSDYEhORFexgxE0S7/95zuGYCgROfm
xvmQra0SMY+efp7uHuCXltWJak16w/HovHc2GozbLVUUWdGa/NKy2xxTrevH93e3048314/X9/d3
9612K1HGyBXNvc9SY2VqhXrJC4zqLBVhllqpUyN0+ixjHYksV4W0mDLYu9QxbTyZffjbsNPt9Dv5
WhYnpghPZmXxrLHjgwT9vw1fP2NvrFPsHfZ+bbfyuFzptDWxRanarTCLFHE86IN0aZTIs/BJ2QTr
53OLE+fz92tl7DcgMhgcWANWVWqzYusXfqyeecfwwA5FC+Zzx8d8PuW/1zTIW0aHtqRWW5xwzX95
2fjAslTZTVY8gXaR2SzM4vn8Morcpqmkdbz19LeZ2j/oSiYw1p+37mnH4hkI0N9z/A1jaYx4pXEY
1ao0MsIJ92eJ03SSxyoBCSNutMG0KsQvoDLsgsrc0q8e/8rLRaxD8ZVZwTGW+kVciK/sWpvg25Wy
cJulXh0d88PRvDX78DjlVfPWMfE2JDsK/NvR2VGpKPLCwd5hCfwAS7o8NdybkoVKpcGkLAq5PXLH
jPaWhGWBRfYGWoyxcN6at3jVuBbttLl+WaYhebXI0utULmJ1dExrzngN6+TcS0H/dsLPVPGsCi+8
U+2tTGEiHivUivRasJ3MEW8Tbf7DPI+coud2R/AmW/nNOl1mR+8nkw/319efRAcivDbpkYu6Y3GT
yUhFf/AKH/X2qRr5rO6VycoiVLDPSSHTp842iXk5ws8WMkTE/dB61xVHx5M9J3TyBd+GhTTrqzLJ
jxZZFiuZHrd+bLdW5DIypmjFKgIMnNzrUHgvSh1HrUkX0e09vzU5xZPMNdb0wXcXq1ba4qn7L/7D
hkI+xXpBezpnTKFMJWFe60an5YtIzajbH/e7HZ0HvfOzoH8ajM86CELR74w7g34A+Eqffw5kEo2H
4l1PzG6n4mFdiltZiLHojSeD4WQ4Frez/xX9bm8oXs7Gj2OSJ1/nOOUUfA/w9DNCCY8DLwYmHzNT
cYEBfoj5ocY3Q2r6iPDVoYyv1PMDFMljXoI3U+19pXZ6GJGlXWeFIWtN2Uy3MJN4UDIRMo0EYma7
1CoSi624ksXTF/lMdmKl/wCt95jdSvu9Tg8ORAsU+zxEWsrYAIMjlRNYYBMmTba0V82BRBJav2F4
Pj8gQgzXxNrZw+X9w+cpBjZqYbSFwGkZx1DOlTZ09vdlCr+fquJLVpDj1Go5PL+vm+4jTtzXDull
kW37vW5DAb9T4Kvvp1/m81t6qAWb3s0evtzd31wdEO2WtPGgYjXNCuvCxAv1emZfnEGnvy8MMm8Z
b/cF6f4OQRy9+Tyx+f9Hnpl62d7ePVw1BKmHXhmE/ashwTrb6jTpDZPwrTkqh/x3pal4ILSqufk/
xaG4lAWkAD5XBzDYdQBYKHKsVhTE76b1k3CZTlDVMy/m6buHUom/lKkATvTOJoPRZNCtkGNMCxy9
gFR1Qf4IEF3aiZheCwerjTU5/OCi3xv2aCxRCaqVINaJthej0aB7S6MrSeORuujyGvkS5LHcgvmL
XpeHTC43aUBwqziXXTguNmsIDWLGXmTLJY04LQc/larYXmRpY6hAvedHksxGF5+41AuYcRqUaZoh
Uyp/dCDDtUaG5RrC75NxnG2CZaxX6/pAx5lMdQKz+nVuLMkW1cAyQ34Kain9VhSUUZgV9XP+nPv1
kV4udVjGdnvBWnPJCHVeYJS1Ol2ZCxqOqQJwNtgQdOzGjFJRYwlVyBdX199dfr55oFHSRSdHKYVt
0cX/8L9q1FurzwKXNgsox3q+ChUZm6UqABCCPdZgzTJjWRBnK3KiSqYD9qaI3OVhytbki4JilWpy
uGHpynD2RgHdiQp8ydPgnEhrCjVepQuUSkrYtUKBA0+2a2lFSNa0YoFCMA3jEhUEfog3QUC0ZlmC
nUsi8JqmkUvVFhlmCkMkxaJQ8klsUW54WkIvKTFpTkw4KkNlFlrgDwh/Upua3EmklhL2NGKTpV9b
IfNcIS2TfhPICtHiLdgXXEWx2Ju1SkWZrwoZgUBnnlI8OWKTeSrePawLBW1jCFzEMl2VqMwENRis
MR97RuM5zkBf/8w6pa3oHEIvxf5GMLC2NjeTkxOVdjb6Secq0rKTFasTejqhUvoxWz5+nN09jgfn
Qf+R9kGNNaEJajmVrlCT4qAva0W6EzYDP0jhkFIYW7B+UZmlBh4EvfE0a5M5BR/4hbqGTBqpZx0q
sUYFELORExB24bQ7khEV42Zd2iij0HONHzHj4EiEcWZU1IHnoEI0rCKKc7BCUsO0TRfz7PzBSXFJ
US8IZGi1L3jEs5bir4QyWMJoE/iZiaBejzbO1tgnyacN6krhmXKWlZ6QQGtkICVahZCVcTn9iJVI
LhGpdTcRgKEFZNiRd8V8RWej7Zo9MMlhaJogSljXHHvL4z4RqrMIkQRCBF5I8qLa8r6L5R5K69md
6t990TBulsKNZRQJ9NjO20lW+PcTZJKmLBhOBXx8oUipsIL6qZQxucBKo5MQaAGQeY78kUg3xyDu
zgOEK0KnAB5EjcQEs3TypzJZwMII4UuzTcMHaZ4ENaYI2g7Nf4bhvcGdkLRqXWSAe7ghVpu2YPgU
HmYRJm1BSqtuCkgtyLA0lpQpvISWMO0ZuynkQUAX2QuSgFVQAcTh8Epr1kirjp2PS0IFWkLR3xba
fg3N2YJ3RYoSHHv+q73iCBJQH90njbAMgZdywpQIIRzaMj58iLMFFEuFhXDDgkGYcDBRK7nYWjAk
Zo6VLh/uINyhC2TaaGaMlS0o83kw90OG9bLUcBfED7f0RGUJXKpOdOaHMCV7/iqDHBmFI+kM56yY
SZcdJqI7Z3jiRGABbzL6L2efirR/wjzl99/FPHJtzud7eKz58dSMQEhRGldRxQ2dWbHU6/aHjiv0
FjrjFEixaOjAkJOA566Otx6OAl5F5GO8IkA8KBdpnDqyFCiICIXeCB1+S61OnSjPYs4qFOtu2dzd
u4EGom8XyQ6O6IQ7ghDKqry883Yxie1raagwVyElX8NqIV6djt3eWgBoUuVmJyaKWSenOT7IkJd6
4KReyWIB+wdo9GNXflKEHdQquxOx4vcIvwexm8i05DTf5AIVUAlfOG5XmPDKGbw3OFxdLitsSHZe
1hF3LsfyEzxinZVxVDOigSCbVOxYJ78VOXMOAcfdrpNRvPuOI+ENNrKvuN21UMsiSyqIpb1+Pmii
UsOmEMKb7rUrHPCfxj7qA8J1iXzt9H3DXk+AyIPEGbVCJI1wRXubw7NA0WPcooDqDqqfdrSIVGVm
HyjnY8/nVea2vTafuz2rtjUpuFP8sv+AzJyIUF7Dd53UVV3tD6KJOnv/U1Lz1F/Q1uUiXCN2mXAh
Lbobqmb4nhYJEP7kUYkD0BXDftaB0ULVOZHh5l0TvqoZCvxia4l2WwS9hjNT7uNjA1uxAlgZjR2q
7HItNyyU6CIHd96Abi8GPU8d8T26MKj3AvU3HPf99HMbe8HBAviz0RGqIUZtju+afMDkJ+LUFwa7
ksHVhI2lHXEZIZ7WMl6eoLFwVUyk4Gf+IBzp/C9LmwFZZ+cGrUaddP1CwUdlkIzbLrDp4C86ReUK
seA2il2bcv3naTqtKoVdn0BFEG3aAOvn1CSkeeAfmzUZejK1KFfO/JnHTEHZomCHVi8qLF2xQ+BD
936depbeirgaJl/nHZ1qYqPn65dvRY/qFp+kqMrlk6oKl/cSTPnKd+6tOnEEXMlpxImx0pbwvZNV
6KwEiIxMg/+ql91re1RVj5IKoBTX8PFS76mkOfadEPaw7Kx+S+C2TEQS0v21a4cgEL+dIXbhvfB3
xje5Rx8gTA2lbRwPhdi33HC4sxe8+3T3cD0RDOD472/tYT8iVL+fYPb8yTV7tbdc7hk+RPMCUPKy
skNydgMn5ID0NguZ2mcjQkWX5MgjqZGncZ/ZPIDsD1dw6MrqGUU+Cbig9ym7w456iLkDp7RFHxO9
QxPKhp1jjn+jmlywOzwQZeoM/ZWPUMA4dx5VEc6S3IPvmnPCFO7KqBAjZJHxRm6No+3pNLRISOVw
nbrpctf+YVm7NqA0YsRlDwGtWzihkXm6gRutVfHKE7PVijskg9aLOK5DDMQ96Am/syr8EVBwUbN2
Fku5G3QryG+a9woEam3uCv4E+4cFoV7xtal7GFt36is0fuUChVJyslt58sWR9S9sdq2bP66hnO8p
Ocl0W9Uijkl6V8qOTx5Q8RiVVPT9UUxLaKtuUAp02WjmoyyZtxyIotND6+HpUVLz+vMjE+GXQ7V7
WZr1eplkZdpM88ZX5pV/kGeRoakxBFH6yXb6ra2ywGjk3MrR2K8tRO+8f3A3y58qd0OxUI7aQi0p
3/AVH1mf9FNTdRd/jQTn8ttMPgN4ybSaLmIUNdn51l86ec+sy1ZW4VLSu7Uq+flktSxjXpYZoEhA
6KlDVzBwo13QTQ9iFmQrVf09c77CPYRMKIwTzohURtTy13jrjEEKrYxxK1+EfK0XdLohVwG7UN2z
xZDx496F2m6bt4P03DF+uq0eElzEDShd0A1rUOaRZHepfDWMlXSH8J3vrtZxjO/a94r3zlvmfWra
SM3XOT+VqlTevn4/IzKPBwbGmoizf4tanuVl7Kn531SAvCI8TxkuA2iPmHb3yAH7kSFNkioT+niB
4MeP9jxy08XsRLgSvjIpvb8sc5S0rq53Dsm47spJTwtUTmmXP5CIUgRBEDqoHuQxmSw0PN8t8XfC
7iZm4sCVLo3oHapwox5enZM47/X9Wp13yK8DujrcH6nxdW8UBQi9L965wToj2/ORncZFMspd5i/N
0m1CzRxHiIF+Tc0odad+WuymmWH4mhRytUJh4K+A6hs6wml6k/x0WBrHD5Ezh/iJNdKeY+H6RVLe
dw9UOMF5/LulifA/eAqWpeZ/In6gnwGSXZtvA37ksihzwSma96sEMfUt6kqQxqiWoELPFeFP4sjX
Yx0sOO7UguzCaM0vIh3tfym9uQ2HSFVtyyKGQmpIET+MUDmenv/IR7z3l/1UrWkcwWvrDpbLLezj
3Ck8/EEaQ3nfSeruGnY9hqCr4kTFltsPboEXZcEwTdfCgvsSw+UIiM7TFZSROHHv8kpVb6XkIKKg
n6U4+gNt4oM/ok92j+SqmAuYYFD7R+WwGgt/Yw7FBQN4Vdw2X0FwMVs1tO5WoXoPxBX7oTcazBjX
RobrUJI9QXWj4Xa+cGw4Ip/KDDgt0GsjQp0hP9WnTcR3N5cPk/43p+3R+UuvPXgZtPvf9L6JUN85
wD2yhcIDwPHirCtWCE3jnoajY37ho/31+u6Vj38Nyt/uGP7oavJL6z1ya+NbBML/xmMe7s2an2Jt
1YC/mDgNIn5N/rP7hKJasggRA+vGAL1fSCNZNIf892P1c1nEjceljoGJzQHb/FxiFTUfkubUGgDl
Xhnj4e+m/tiBHpOFexHSWI6eZJvbpnxWEqvNA2bTmz19oJ9oUthCJfz1hv8lRpjp9Uk3IqB3t6Pu
sHuKn199JBccnavF6fh0qXqncjw+PR+dnS9GYfd0HJ0v5dlZNIiGyPBd8RVoT9esNHqd3ecXeEa/
NFnx90/85UivM8bQvVr6u5OmTOska+rIMF6a10LoxoDNnlSKfNm0Acrbp0It2fTuk4Kt5PeI/Lr9
/v0puYLOWeG9ATT+66//AFWP50k=
===END CRASH DUMP===

**Comment by Taki21** [comment]
I see the problem...will be fixed soon

**Comment by Taki21** [comment]
Now Fixed! Download new release :)
