### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by BogdanMakarchuk** [Inactive-to-Reactive/SurvivalGamesV4#13]
1.Genisys
2. BUG: when you walked into the arena waiting for players and then come out with a full server, and came again, then again you get into the arena and wait for players.
3. ---
4. ---

**Comment by remotevase** [comment]
THIS ISSUE IS PROBLEMATIC FOR THE FOLLOWING REASONS:
1. You deleted the guidelines. You are not supposed to delete them unless you are a team member
2. This issue is not understandable. Had you not deleted the guidelines, you may have realized that and edited your post, but alas, you didn't

**Comment by ImagicalGamer** [comment]
@BogdanMakarchuk I can't understand the issue.
