### ISSUE TITLE
Problem with plugin in Genisys_1.2 software

### ISSUE THREAD

**Issue by NikeboyHU** [Inactive-to-Reactive/SurvivalGamesV4#18]
> ### **DO NOT Delete The Following:**

> ### Please Provide the Issue:

> - Lorum Ispum Dolor Sit...

> ### Sources:

> - ERROR: Lorum Ispum Dolor Sit...

> ### Please provide all that apply to this Issue!
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is written in your native language for maximal clarity
- [ ] This issue does not have abbreveations. Abbreviations make it not understandable.
- [ ] This issue is for SurvivalGamesV4, and not any other plugin.
- [ ] This is not a suggestion, but an actual issue

> ### Please Provide the Server Software Provider:
- [ ] PocketMine-MP
- [ ] ImagicalMine
- [ ] ClearSky
- [ ] Genisys
- [ ] Other...

> ### Other INFO:

> - Lorum Ispum Dolor Sit...

That problem plugin with Genisys_1.2dev server softwer, and logging to server manager Console, error:
19.06 13:49:04 [Multicraft] Received start command
19.06 13:49:04 [Multicraft] Loading server properties
19.06 13:49:04 [Multicraft] Starting server!
19.06 13:49:04 [Multicraft] Loaded config for "Other: Genisys"
19.06 13:49:04 [Multicraft] Server executable "/bing/php7/bin/php" not found, server startup might fail!
19.06 13:49:04 [Server] INFO Failed loading /home/php/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /home/php/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
19.06 13:49:04 [Server] INFO PocketMine-iTX Genisys is a fork of PocketMine-MP, made by iTX Technologies LLC.
19.06 13:49:04 [Server] INFO Version: 1.2dev
19.06 13:49:04 [Server] INFO Target client Version: v0.15.0.0 alpha
19.06 13:49:04 [Server] INFO Latest source code is available at https://github.com/iTXTech/Genisys
19.06 13:49:04 [Server] INFO Donate link: http://pl.zxda.net/plugins/203.html
19.06 13:49:04 [Server] INFO 如果你在免费使用本核心，希望你可以进入上面的链接捐赠给我们，这会成为我们前进的动力。
19.06 13:49:04 [Server] Server thread/INFO Loading pocketmine.yml...
19.06 13:49:04 [Server] Server thread/INFO Loading genisys.yml...
19.06 13:49:05 [Server] Server thread/INFO Loading server properties...
19.06 13:49:05 [Server] Server thread/INFO Selected English (eng) as the base language
19.06 13:49:05 [Server] Server thread/INFO Starting Minecraft: PE server version v0.15.0.0 alpha
19.06 13:49:05 [Server] Server thread/INFO Opening server on [ip don't show for you]
19.06 13:49:05 [Server] INFO sh: 1: ifconfig: not found
19.06 13:49:05 [Server] INFO sh: 1: ifconfig: not found
19.06 13:49:05 [Server] Server thread/INFO This server is running Genisys version 1.2dev "Ikaros" (API 2.0.0)
19.06 13:49:05 [Server] Server thread/INFO Genisys is distributed under the GPL License version 3 and later
19.06 13:49:05 [Server] Server thread/INFO Loading AntiSpam v1.3
19.06 13:49:05 [Server] Server thread/INFO Loading EssentialsPE v2.0.0
19.06 13:49:05 [Server] Server thread/INFO Loading NoAdvertisingPE v1.0.1
19.06 13:49:05 [Server] Server thread/INFO Loading AntiCheat v2.1.0
19.06 13:49:05 [Server] Server thread/INFO Loading ServerAuth v2.13
19.06 13:49:05 [Server] Server thread/INFO Loading ZipPluginLoader v1.1.3
19.06 13:49:05 [Server] Server thread/INFO Loading iProtector v3.1b
19.06 13:49:05 [Server] Server thread/INFO Loading SurvivalGamesV4 v4.0.5
19.06 13:49:05 [Server] Server thread/INFO Loading PurePerms v1.3.7
19.06 13:49:05 [Server] Startup Done (0.744s)! For help, type "help" or "?"
19.06 13:49:20 [Multicraft] Skipped 49 lines due to rate limit (30/s)  
19.06 13:49:21 [Server] INFO Notice: Undefined property: SurvivalGamesV4\SurvivalGamesV4::$pl in phar:///plugins/SGV4.0.5.phar/src/SurvivalGamesV4/SurvivalGamesV4.php on line 116
19.06 13:49:21 [Server] Server thread/CRITICAL "Could not pass event 'pocketmine\event\player\PlayerRespawnEvent' to 'SurvivalGamesV4 v4.0.5': Call to a member function addEffect() on null on SurvivalGamesV4\SurvivalGamesV4
19.06 13:49:21 [Server] Server thread/CRITICAL Error: "Call to a member function addEffect() on null" (EXCEPTION) in "/SGV4.0.5.phar/src/SurvivalGamesV4/SurvivalGamesV4" at line 125
19.06 13:50:45 [Server] INFO Warning: Illegal offset type in isset or empty in phar:///Genisys_1.2dev.phar/src/pocketmine/entity/Entity.php on line 381
19.06 13:50:45 [Server] INFO Warning: Illegal offset type in isset or empty in phar:///Genisys_1.2dev.phar/src/pocketmine/entity/Entity.php on line 381
19.06 13:50:46 [Server] INFO Notice: Undefined property: SurvivalGamesV4\SurvivalGamesV4::$pl in phar:///plugins/SGV4.0.5.phar/src/SurvivalGamesV4/SurvivalGamesV4.php on line 116
19.06 13:50:46 [Server] Server thread/CRITICAL "Could not pass event 'pocketmine\event\player\PlayerRespawnEvent' to 'SurvivalGamesV4 v4.0.5': Call to a member function addEffect() on null on SurvivalGamesV4\SurvivalGamesV4
19.06 13:50:46 [Server] Server thread/CRITICAL Error: "Call to a member function addEffect() on null" (EXCEPTION) in "/SGV4.0.5.phar/src/SurvivalGamesV4/SurvivalGamesV4" at line 125

**Comment by Taki21** [comment]
U dont have the latest release. I will post it soon.
