### ISSUE TITLE
I cant write something to a sign

### ISSUE THREAD

**Issue by Heroata** [Inactive-to-Reactive/SurvivalGamesV4#19]
When I try to put any sign, a sign template appearing which writes [running]bla bla so I cant write anything to a sign.

(in genisys for 0.14.x's latest release)

**Comment by Taki21** [comment]
yes i have seen this issue. I am currently planning to rewrite this plugin!

**Comment by remotevase** [comment]
we are rewriting this plugin. If you would like to try to fix this, it will likely be in this file: https://github.com/Inactive-to-Reactive/SurvivalGamesV4/blob/re-write/src/SurvivalGamesV4/events/Interact.php

**Comment by Heroata** [comment]
Very nice! My friend developed a map reset for this plugin. I'm gonna tell him the new project.

**Comment by remotevase** [comment]
Map resets are for Hunger Games plugins because hg plugins allow block breaking.
This plugin is a Survival Games plugin because it does not allow block breaking and therefore does not need a map reset!

**Comment by Heroata** [comment]
Oh I wasn't know but what about adding cake and breaking tree leafs?

**Comment by remotevase** [comment]
Those are cancelled as well
