### ISSUE TITLE
cannot talk

### ISSUE THREAD

**Issue by biswarm22** [Inactive-to-Reactive/SurvivalGamesV4#27]
> ### **DO NOT Delete The Following:**

> ### Please Provide the Issue:
in game players cannot talk with other players out of the game and the plugin makes the chat not appear on console. removed this plugin and the chat appears on console again
> - Lorum Ispum Dolor Sit...

> ### Sources:

> - ERROR: Lorum Ispum Dolor Sit...

> ### Please provide all that apply to this Issue!
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is written in your native language for maximal clarity
- [x] This issue does not have abbreveations. Abbreviations make it not understandable.
- [x] This issue is for SurvivalGamesV4, and not any other plugin.
- [x] This is not a suggestion, but an actual issue

> ### Please Provide the Server Software Provider:
- [ ] PocketMine-MP
- [ ] ImagicalMine
- [ ] ClearSky
- [x] Genisys
- [ ] Other...

> ### Other INFO:

> - Lorum Ispum Dolor Sit...

**Comment by ImagicalGamer** [comment]
This isn't an issue it's per-world chat. I believe it can be disabled in the config.

**Comment by biswarm22** [comment]
@ImagicalGamer I don't see it on config, which one is it?

**Comment by ImagicalGamer** [comment]
config.yml

**Comment by ImagicalGamer** [comment]
:stuck_out_tongue_winking_eye:

**Comment by biswarm22** [comment]
@ImagicalGamer no I mean I cannot see the option to disable it in the cobfig, I am looking at the latest one

**Comment by remotevase** [comment]
hmm... idk...
