### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by remotevase** [Inactive-to-Reactive/SurvivalGamesV4#3]
DO NOT DELETE THIS!!!!!

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, PLEASE TICK THE CHECKBOXES BY CLICKING ON THEM! 
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is written in your native language for maximal clarity
- [x] This issue does not have abbreveations. Abbreviations make it not understandable.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.
- [x] This is not a suggestion, but an actual issue<br> <br>

NOTE: If it is a suggestion, title it [SUGGESTION] ______

If all the checkboxes are checked, congratulations! Fill out the fields below
! = required

! <--STATE SERVER PROVIDER HERE (EG POCKETMINE, IMAGICALMINE, GENYSIS etc)-->

! <--STATE ISSUE HERE--> I do not know how this occurs it keeps repeating

<--PUT ANY CONSOLE ERRORS HERE--> [13:06:15] critical> Could not execute task SurvivalGamesV3\GameSender: Call to a member function clearAll() on null
[13:06:15] critical> Error: "Call to a member function clearAll() on null" (EXCEPTION) in "/SurvivalGamesV3DMFix.phar/src/SurvivalGamesV3/SurvivalGamesV3" at line 795

<--IF CRASH DUMPS ARE AVAILABLE, PASTE THE ENTIRE FILE'S CONTENTS HERE-->

**Comment by Mike4l6** [comment]
Notice the SurvivalGamesV3**DM**Fix.phar but this is caused in all versions

**Comment by remotevase** [comment]
I have not gotten this issue...

**Comment by Taki21** [comment]
Checked Code, This may be from an old version

**Comment by remotevase** [comment]
Yes, it is. DMFix is from quite a while back

**Comment by Taki21** [comment]
Is all features done?  I wanna do SG4 Already

**Comment by remotevase** [comment]
Well, they're done, not tested...

**Comment by Taki21** [comment]
All done + tested by me except the random chest

**Comment by Taki21** [comment]
Random Chest => V4 (Major Feature)

**Comment by remotevase** [comment]
Yeah. Once random chest is tested, **then** we change all the numbers to 4 instead of 3, then we will be good! (Not before it is tested. It always works better that way for me IDK why)

**Comment by Taki21** [comment]
Its better we do V4 then V5 and we can name the updates lel

**Comment by Taki21** [comment]
After all its a big update V4 im making a todo

**Comment by remotevase** [comment]
First you (i cant) test the chest customization, then we do all the V4 stuff, then we post update

**Comment by Taki21** [comment]
so is chest thingy be part of V4? Its better i think

**Comment by Taki21** [comment]
v3 is for classic SG

**Comment by remotevase** [comment]
Ya, chest thing is part of V4

**Comment by Taki21** [comment]
ok ill mention u in 3 to 5 min in new todo

**Comment by remotevase** [comment]
ok
