### ISSUE TITLE
Memory increases when no one is on

### ISSUE THREAD

**Issue by NML32** [Inactive-to-Reactive/SurvivalGamesV4#5]
DO NOT DELETE THIS!!!!!

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, PLEASE TICK THE CHECKBOXES BY CLICKING ON THEM! 
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is written in your native language for maximal clarity
- [x] This issue does not have abbreveations. Abbreviations make it not understandable.
- [x] This issue is for SurvivalGamesV3, and not any other plugin.
- [x] This is not a suggestion, but an actual issue<br> <br>

NOTE: If it is a suggestion, title it [SUGGESTION] ______

If all the checkboxes are checked, congratulations! Fill out the fields below
! = required

! <--STATE SERVER PROVIDER HERE (EG POCKETMINE, IMAGICALMINE, GENYSIS etc)-->
Genisys 1.1dev-435
! <--STATE ISSUE HERE-->
Memory keeps increasing when no one is in game. This only happens when SurvivalGames plugin is installed. 
<--PUT ANY CONSOLE ERRORS HERE-->
No errors.
<--IF CRASH DUMPS ARE AVAILABLE, PASTE THE ENTIRE FILE'S CONTENTS HERE-->
No crash dump

**Comment by Taki21** [comment]
Answer: The Plugin is pretty big with multiple tasks going on even without people on....maybe a code cleanup will help

**Comment by remotevase** [comment]
Yeah, it should

**Comment by Taki21** [comment]
SGV4 Might Fix this (Soon)

**Comment by NML32** [comment]
you guys are funny. You say might fix it and close the ticket.

**Comment by Taki21** [comment]
Lel said code cleanup : )

**Comment by Taki21** [comment]
lots of unnecessary poop lying around in da code

**Comment by NML32** [comment]
I switched from Genisys to Imagicalmine to test and I'm seeing the same memory increase with SG plugin running. I've downloaded the latest SG plugin from your Official download link.  
I'm not so sure this is just a Genisys issue as the label states.

**Comment by remotevase** [comment]
Yeah, idk why DAT was dere. I should have removed long ago XD

**Comment by Taki21** [comment]
hmm

**Comment by Taki21** [comment]
really weird

**Comment by Leo3418** [comment]
I believe this bug is related to PHP version. It occurs on PHP 7 but does not occur on PHP 5.

**Comment by Taki21** [comment]
@Leo3418 Are u sure? Just asking but did u have sg plugin for PHP5 before? did it happen? Please let me know! Thx :P

**Comment by Leo3418** [comment]
@Taki21 Of course, I used this plugin on ClearSky PHP 5 and worked fine. But recently ClearSky was updated to PHP 7, and this bug appears on both ClearSky PHP 7 and Genisys.

**Comment by Taki21** [comment]
Thx @Leo3418! :P No more issues lel
