### ISSUE TITLE
NULL

### ISSUE THREAD

**Issue by Taki21** [Inactive-to-Reactive/SurvivalGamesV4#6]
Please Do NOT Delete The Following:

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, Select all that Apply to your Issue:
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is written in your native language for maximal clarity
- [ ] This issue does not have abbreveations. Abbreviations make it not understandable.
- [ ] This issue is for SurvivalGamesV3, and not any other plugin.
- [ ] This is not a suggestion, but an actual issue<br> <br>

#### NOTE: If it is a suggestion, title it [SUGGESTION] ______

If all the checkboxes are checked, congratulations! Fill out the fields below:
[!] = required

**Comment by NML32** [comment]
Memory increases when no one is on #5
Why did you close and lock my bug report #5 ?  Not sure why you locked it?
If I remove SG plugin memory stops increasing this is a big problem.

**Comment by Taki21** [comment]
-_0

**Comment by Taki21** [comment]
That has nothing to do with plugin

**Comment by Taki21** [comment]
Genisys Right? Well Genisys is really screwed in their memory. I tried Genisys and had the same stupid problem. Its a problem with Genisys

**Comment by NML32** [comment]
then why does the problem go away when I remove your plugin?  I'm watching the memory climb while SG plugin is installed.

**Comment by Taki21** [comment]
Someone else had this problem and it turned out it was his server provider

**Comment by Taki21** [comment]
We will try to figure it out
