### ISSUE TITLE
Code Cleanup Instructions

### ISSUE THREAD

**Issue by remotevase** [Inactive-to-Reactive/SurvivalGamesV4#9]
1. Make a branch called rewrite
2. In the src, make a Loader.php file
3. Divide the SG file into multiple parts
4. Put the enable and disable into Loader.php
5. Split up the rest of the SG file into sperate files
6. Test it!

**Comment by bbka123** [comment]
This is a good job

**Comment by Taki21** [comment]
@remotevase Do we need  ur Random Chest Branch Anymore?

**Comment by remotevase** [comment]
no

**Comment by remotevase** [comment]
wait...

**Comment by Taki21** [comment]
ok

**Comment by Taki21** [comment]
um no loader.php....for several reasons:
a) making another file will ruin SOME code
b) we need to do more work changing the code
c) u get the point breh....

**Comment by remotevase** [comment]
Well, duh! Of course it will ruin some code! That's why we will fix it! Plus, loader.php speeds up the plugin, a lot, as well as setting the stage for more organization! Keep in mind that this will be in a different branch until we get it working!

**Comment by Taki21** [comment]
Well that wont help:
Code cleanup as in unneeded code, who needs a branch when i know 200 lines of uselss code now!

**Comment by Taki21** [comment]
Making another file will make it more complicating trust me

**Comment by remotevase** [comment]
Hmm, okay, but organization will be key, and I will start work on that soon

**Comment by Taki21** [comment]
Yup Maybe we can "cleanup the organization in the 960 lines SG File lel"

**Comment by remotevase** [comment]
Yup

**Comment by remotevase** [comment]
But you work on features, I'll work on the new organization of the project for speed, k? Trust me, although it might be more complicated, it is definitely a great speedup

**Comment by Taki21** [comment]
ok

**Comment by ImagicalGamer** [comment]
Remove everywhere that it checks if something is enabled in the config, it slows the plug down. Check those on enable and then you can do `protected $lightning = true` and `if($this->lightning == true) //continue`

**Comment by Taki21** [comment]
ya but that will effect the update wouldnt it?

**Comment by Taki21** [comment]
the Customizalbe update

**Comment by ImagicalGamer** [comment]
Yes we can update that same way we did with the mode for setting spawns, `$this->lightning = true`
